# -*- coding: utf-8 -*-
"""Chatbots With Langgraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9jo71_S8N2WxHDB_yRiJO31VrOkeDOm

## Chatbots with Langgraph
"""

!pip install langgraph langsmith

!pip install langchain langchain_groq langchain_community

from google.colab import userdata
groq_api_key = userdata.get('GROQ_API_KEY')
langsmith_api_key = userdata.get('LANGCHAIN_API_KEY')

import os
os.environ['LANGCHAIN_API_KEY'] = langsmith_api_key
os.environ['LANGCHAIN_TRACKING_V2'] = 'true'
os.environ['LANGCHAIN_PROJECT'] = 'CourseLanggraph'

from langchain_groq import ChatGroq

llm = ChatGroq(groq_api_key = groq_api_key,model='llama-3.3-70b-versatile')
llm

"""## Start building chatbot using langgraph"""

from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import START,END,StateGraph
from langgraph.graph.message import add_messages

class State(TypedDict):
  # Messages have the type "list". The `add_messages` function
    # in the annotation defines how this state key should be updated
    # (in this case, it appends messages to the list, rather than overwriting them)
  messages:Annotated[list,add_messages]

graph_builder = StateGraph(State)

graph_builder

def chatbot(state:State):
  return {"messages":llm.invoke(state['messages'])}

graph_builder.add_node("chatbot",chatbot)

graph_builder

graph_builder.add_edge(START,"chatbot")
graph_builder.add_edge("chatbot",END)

graph=graph_builder.compile()

from IPython.display import Image, display
try:
  display(Image(graph.get_graph().draw_mermaid_png()))
except Exception:
  pass

while True:
  user_input=input("User: ")
  if user_input.lower() in ["quit","q"]:
    print("Good Bye")
    break
  for event in graph.stream({'messages':("user",user_input)}):
    print(event.values())
    for value in event.values():
      print(value['messages'])
      print("Assistant:",value["messages"].content)

